---
- hosts: mysql
  vars:
    password: zoblesmouches42
  tasks:
  - name: install mysql
    apt: name={{item}} state=latest
    with_items:
      - mariadb-server
      - python-pymysql
      - python-mysqldb
      - mycli
  - name: configure mysql
    copy: src=mysql/99-openstack.cnf dest=/etc/mysql/mariadb.conf.d/99-openstack.cnf
    notify:
      - restart mysql
  - name: create databases
    mysql_db: name={{item}} state=present
    with_items:
      - keystone
      - nova
      - nova_api
      - nova_cell0
      - neutron
      - glance
  - name: create users
    mysql_user: name={{item}} password={{password}} priv=*.*:ALL state=present
    with_items:
      - keystone
      - nova
      - neutron
      - glance
  - name: ensure mysql is running
    service:
      name: mysql
      state: started
  handlers:
  - name: restart mysql
    service:
      name: mysql
      state: restarted
