---
- hosts: mysql
  vars:
    password: zoblesmouches42
  tasks:
  - import_tasks: common.yml

  - name: add apt key for mariadb
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: f1656f24c74cd1d8
  - name: add apt repository for mariadb
    apt_repository:
      repo: deb [arch=amd64,i386,ppc64el] http://mariadb.kisiek.net/repo/10.1/ubuntu xenial main
      state: present
  - name: install mysql
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - mariadb-server
      - python-pymysql
      - python-mysqldb
      - mycli
  - name: configure mysql
    copy: src=mysql/99-openstack.cnf dest=/etc/mysql/conf.d/99-openstack.cnf
    notify:
      - restart mysql
  - name: create databases
    mysql_db: name={{item}} state=present
    with_items:
      - keystone
      - nova
      - nova_api
      - nova_cell0
      - neutron
      - glance
  - name: create users
    mysql_user: name={{item}} password={{password}} priv=*.*:ALL state=present host=%
    with_items:
      - keystone
      - nova
      - neutron
      - glance
  - name: ensure mysql is running
    service:
      name: mysql
      state: started
  handlers:
  - name: restart mysql
    service:
      name: mysql
      state: restarted
